### PR TITLE
Early code for search intention analysis

### PR DESCRIPTION
**Pull request by taceybadgerbrook**
These three pieces of code have been sitting on my machine. It's just a good idea to put them somewhere safe.

### CODE REVIEW

**Comment by harrisonpim** [comment]
fab - happy to get these bits of analysis stored here 😁 
are the outputs intentionally left in these notebooks? if not, it might be worth rerunning nbstripout and resubmitting a fresh PR

**Comment by taceybadgerbrook** [comment]
That’s odd. I’ll have another go.

Hope you’re feeling better today!

**Comment by taceybadgerbrook** [comment]
I stripped out the outputs and recommitted and Github seems happy enough to put this all in one PR. If it really gums things up let me know.

**Review by harrisonpim — APPROVED** [review]

**Comment by harrisonpim** [comment]
good stuff! i'll let you squash and merge those commits

**Pull request merged**
