### PR TITLE
demo functionality for weco api and reporting cluster

### PR DESCRIPTION
**Pull request by harrisonpim**

### CODE REVIEW

**Review by taceybadgerbrook — APPROVED** [review]
Thanks very much for putting these libraries together. They are going to make things a whole lot easier for me.

I only have one comment for the images.py file. Could you add the id number and any title or name to the list of fields?

**Comment by harrisonpim** [comment]
> Could you add the id number and any title or name to the list of fields?

Not exactly...

FYI, the list of fields isn't something I'm setting myself - I'm just replicating the fields which the API accepts. You can see the complete list in [the docs on developers.wellcomecollection.org](https://developers.wellcomecollection.org/images). 

However, if you already know the image ID you're looking for you should be able to get a result with `get_image(query_id)`. Likewise if you're looking for a known title, `image_search(query="whatever your title is")`.

**Comment by taceybadgerbrook** [comment]
Ok, good to know.
________________________________

**Comment by harrisonpim** [comment]
🎉  looking forward to adding some features together in the new year!

**Pull request merged**
